# Generated by Django 2.1.7 on 2019-03-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='infoconcert_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='infoconcert_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
