# Generated by Django 2.1.7 on 2019-04-01 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('festivals', '0002_auto_20190330_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.Festival')),
            ],
        ),
        migrations.CreateModel(
            name='PartyInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='festivals.Party')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_invites', to='festivals.Participation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='festivals.Participation')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='festivals.Participation')),
                ('assignor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_tasks', to='festivals.Participation')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='festivals.Party')),
            ],
        ),
        migrations.AddField(
            model_name='participation',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='festivals.Party'),
        ),
    ]
